In [1]:
import pandas as pd
import numpy as np
import math as m

In [2]:
data=pd.read_csv('data.csv')
data_T=pd.DataFrame(data, columns= ['Object','Property','Value','Source'])
data_T

       Object   Property   Value   Source
0     Object1  Property1  179475  Source1
1     Object1  Property3  371893  Source1
2     Object2  Property1  422854  Source1
3     Object2  Property3  324512  Source1
4     Object3  Property1  489481  Source1
..        ...        ...     ...      ...
145   Object6  Property2  319997  Source4
146   Object7  Property2  269456  Source4
147   Object8  Property2  323152  Source4
148   Object9  Property2  286530  Source4
149  Object10  Property2  856218  Source4

[150 rows x 4 columns]

In [3]:
data_T['TSInitial']=0.8
data_T['C_v']=0.0
data_T.head(5)

    Object   Property   Value   Source  TSInitial  C_v
0  Object1  Property1  179475  Source1        0.8  0.0
1  Object1  Property3  371893  Source1        0.8  0.0
2  Object2  Property1  422854  Source1        0.8  0.0
3  Object2  Property3  324512  Source1        0.8  0.0
4  Object3  Property1  489481  Source1        0.8  0.0

In [4]:
# Definition de la matice de similarite
def similarity(dataframe):
    dict_sim = {}
    for key, df in dataframe.groupby(by=['Object','Property']):
        Values = df['Value'].unique()
        row = key[0]+key[1]
        for  i in range(len(Values)):
            w1 = Values[i]
            for  u in range(len(Values)):
                w2 = Values[u]
                sim = 1
                if w1!=w2:
                    t = abs(w1-w2)
                    sim = 1/t
                dict_sim[row+str(w1)+str(w2)] = sim
                dict_sim[row+str(w2)+str(w1)] = sim
    return dict_sim

In [5]:
import math
def Ts(df):
    ts_list = df['TSInitial'].to_list()
    return sum([-math.log(1-ts) for ts in ts_list])
def cos_sim(a,b):
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

In [6]:
import time as t
from natsort import index_natsorted, order_by_index
def TruthFinder_seq(data_T):
    ni=5
    trustold = 0.00001
    start = t.time()
    nb_iter_do = 0
    rho=0.7
    lam=0.5
    dict_sim=similarity(data_T)
    for i in range(ni):
        df = data_T[['Source', 'TSInitial']].drop_duplicates().reindex(index=order_by_index(data_T[['Source', 'TSInitial']].drop_duplicates().index, index_natsorted(data_T[['Source', 'TSInitial']].drop_duplicates()['Source'], reverse=False)))
        ts1=df['TSInitial']
        grouped_df = data_T.groupby(["Object", "Property","Value"])
        for key,item in grouped_df:
            sum_ = Ts(item)
            data_T.loc[((data_T["Object"] == key[0]) & (data_T["Property"]==key[1]) & (data_T["Value"]==key[2])), "C_v"]=sum_
        grouped_df=data_T.groupby(["Object", "Property","Value"])
        for key ,item in grouped_df:
            cv=data_T.loc[((data_T["Object"] == key[0]) & (data_T["Property"]==key[1]) & (data_T["Value"]==key[2])), "C_v"].values[0]
#             print(cv)

            data_d=data_T.loc[((data_T["Object"] == key[0]) & (data_T["Property"]==key[1]) & (data_T["Value"]!=key[2])), ["Value","C_v"]]
            for row in data_d.values:
                Key_sim=key[0]+key[1]+str(key[2])+str(int(row[0]))
                cv+=rho*(row[1]*dict_sim[Key_sim])
            cv=1/(1+np.exp(-lam*cv))
        #     print(cv)
            data_T.loc[((data_T["Object"] == key[0]) & (data_T["Property"]==key[1]) & (data_T["Value"]==key[2])), "C_v"]=cv
        groupe_ts=data_T.groupby(['Source'])
        for key,item in groupe_ts:
            ts_=item['C_v'].mean()
            data_T.loc[((data_T["Source"] == key)), "TSInitial"]=ts_
        df = data_T[['Source', 'TSInitial']].drop_duplicates().reindex(index=order_by_index(data_T[['Source', 'TSInitial']].drop_duplicates().index, index_natsorted(data_T[['Source', 'TSInitial']].drop_duplicates()['Source'], reverse=False)))
        ts2=df['TSInitial']
        print('ItÃ©ration : ',i+1)
        print(1-abs(cos_sim(ts1,ts2)))
        nb_iter_do = i+1
        if 1-abs(cos_sim(ts1,ts2)) < trustold:
            break
    end = t.time()

    return data_T,end-start,nb_iter_do

In [7]:
result_=TruthFinder_seq(data_T)

ItÃ©ration :  1
0.0010838208531832594
ItÃ©ration :  2
0.0003308709164125956
ItÃ©ration :  3
7.630389246815472e-05
ItÃ©ration :  4
1.5615056022988405e-05
ItÃ©ration :  5
3.079325279098377e-06

In [8]:
result_

(       Object   Property   Value   Source  TSInitial       C_v
 0     Object1  Property1  179475  Source1   0.811842  0.926623
 1     Object1  Property3  371893  Source1   0.811842  0.926623
 2     Object2  Property1  422854  Source1   0.811842  0.926624
 3     Object2  Property3  324512  Source1   0.811842  0.926623
 4     Object3  Property1  489481  Source1   0.811842  0.926623
 ..        ...        ...     ...      ...        ...       ...
 145   Object6  Property2  319997  Source4   0.672421  0.754948
 146   Object7  Property2  269456  Source4   0.672421  0.754948
 147   Object8  Property2  323152  Source4   0.672421  0.754948
 148   Object9  Property2  286530  Source4   0.672421  0.754948
 149  Object10  Property2  856218  Source4   0.672421  0.637053

 [150 rows x 6 columns],
 2.1472740173339844,
 5)

In [9]:
def res(result):
    gr=result.groupby(["Object", "Property"])
    data_out={'Object':[],'Property':[],'Value':[]}
    for key,item in gr:
#         print(item.values)
        cv_max=0
        value_pred=None
        for line in item.values:
#             print(line[5])
            if cv_max<line[5]:
                cv_max=line[5]
                value_pred=line[2]
        data_out['Object'].append(key[0])
        data_out['Property'].append(key[1])
        data_out['Value'].append(value_pred)
    return pd.DataFrame(data_out)

In [11]:
res_=res(result_[0])
# len(res_)

In [12]:
list_ = res_.to_numpy()

In [13]:
data_truth=pd.read_csv('data_truth.csv')
data_truth_=pd.DataFrame(data_truth, columns= ['Object','Property','Value'])

In [18]:
list__=data_T.to_numpy()
list__

array([['Object1', 'Property1', 179475, 'Source1', 0.8118422091111772,
        0.9266232393428846],
       ['Object1', 'Property3', 371893, 'Source1', 0.8118422091111772,
        0.926623243351792],
       ['Object2', 'Property1', 422854, 'Source1', 0.8118422091111772,
        0.9266235317569093],
       ['Object2', 'Property3', 324512, 'Source1', 0.8118422091111772,
        0.9266232837540324],
       ['Object3', 'Property1', 489481, 'Source1', 0.8118422091111772,
        0.9266233385146302],
       ['Object3', 'Property3', 122120, 'Source1', 0.8118422091111772,
        0.9266232074406593],
       ['Object4', 'Property1', 433866, 'Source1', 0.8118422091111772,
        0.9266232898374499],
       ['Object4', 'Property3', 292202, 'Source1', 0.8118422091111772,
        0.9266232902537472],
       ['Object5', 'Property1', 230773, 'Source1', 0.8118422091111772,
        0.9266232248882954],
       ['Object5', 'Property3', 205622, 'Source1', 0.8118422091111772,
        0.926623214901834],
       ['Object6', 'Property1', 195647, 'Source1', 0.8118422091111772,
        0.9266232315354692],
       ['Object6', 'Property3', 327221, 'Source1', 0.8118422091111772,
        0.9266232565987541],
       ['Object7', 'Property1', 337793, 'Source1', 0.8118422091111772,
        0.9266232257763465],
       ['Object7', 'Property3', 361249, 'Source1', 0.8118422091111772,
        0.9266233207044674],
       ['Object8', 'Property1', 433516, 'Source1', 0.8118422091111772,
        0.9266235030519351],
       ['Object8', 'Property3', 359345, 'Source1', 0.8118422091111772,
        0.6970598348394299],
       ['Object9', 'Property1', 423905, 'Source1', 0.8118422091111772,
        0.6970609416769235],
       ['Object9', 'Property3', 217310, 'Source1', 0.8118422091111772,
        0.6970599653642082],
       ['Object10', 'Property1', 421773, 'Source1', 0.8118422091111772,
        0.697060327960422],
       ['Object10', 'Property3', 307304, 'Source1', 0.8118422091111772,
        0.6970602854209861],
       ['Object1', 'Property1', 179475, 'Source3', 0.8185695437826259,
        0.9266232393428846],
       ['Object1', 'Property3', 371893, 'Source3', 0.8185695437826259,
        0.926623243351792],
       ['Object2', 'Property1', 422854, 'Source3', 0.8185695437826259,
        0.9266235317569093],
       ['Object2', 'Property3', 324512, 'Source3', 0.8185695437826259,
        0.9266232837540324],
       ['Object3', 'Property1', 489481, 'Source3', 0.8185695437826259,
        0.9266233385146302],
       ['Object3', 'Property3', 122120, 'Source3', 0.8185695437826259,
        0.9266232074406593],
       ['Object4', 'Property1', 433866, 'Source3', 0.8185695437826259,
        0.9266232898374499],
       ['Object4', 'Property3', 292202, 'Source3', 0.8185695437826259,
        0.9266232902537472],
       ['Object5', 'Property1', 230773, 'Source3', 0.8185695437826259,
        0.9266232248882954],
       ['Object5', 'Property3', 205622, 'Source3', 0.8185695437826259,
        0.926623214901834],
       ['Object6', 'Property1', 195647, 'Source3', 0.8185695437826259,
        0.9266232315354692],
       ['Object6', 'Property3', 327221, 'Source3', 0.8185695437826259,
        0.9266232565987541],
       ['Object7', 'Property1', 337793, 'Source3', 0.8185695437826259,
        0.9266232257763465],
       ['Object7', 'Property3', 361249, 'Source3', 0.8185695437826259,
        0.9266233207044674],
       ['Object8', 'Property1', 433516, 'Source3', 0.8185695437826259,
        0.9266235030519351],
       ['Object8', 'Property3', 977818, 'Source3', 0.8185695437826259,
        0.7008517848266201],
       ['Object9', 'Property1', 663325, 'Source3', 0.8185695437826259,
        0.7008979631744194],
       ['Object9', 'Property3', 895064, 'Source3', 0.8185695437826259,
        0.7008415978399395],
       ['Object10', 'Property1', 786290, 'Source3', 0.8185695437826259,
        0.7008441079325426],
       ['Object10', 'Property3', 724616, 'Source3', 0.8185695437826259,
        0.7008423764543623],
       ['Object1', 'Property1', 179475, 'Source5', 0.8185682944847634,
        0.9266232393428846],
       ['Object1', 'Property3', 371893, 'Source5', 0.8185682944847634,
        0.926623243351792],
       ['Object2', 'Property1', 422854, 'Source5', 0.8185682944847634,
        0.9266235317569093],
       ['Object2', 'Property3', 324512, 'Source5', 0.8185682944847634,
        0.9266232837540324],
       ['Object3', 'Property1', 489481, 'Source5', 0.8185682944847634,
        0.9266233385146302],
       ['Object3', 'Property3', 122120, 'Source5', 0.8185682944847634,
        0.9266232074406593],
       ['Object4', 'Property1', 433866, 'Source5', 0.8185682944847634,
        0.9266232898374499],
       ['Object4', 'Property3', 292202, 'Source5', 0.8185682944847634,
        0.9266232902537472],
       ['Object5', 'Property1', 230773, 'Source5', 0.8185682944847634,
        0.9266232248882954],
       ['Object5', 'Property3', 205622, 'Source5', 0.8185682944847634,
        0.926623214901834],
       ['Object6', 'Property1', 195647, 'Source5', 0.8185682944847634,
        0.9266232315354692],
       ['Object6', 'Property3', 327221, 'Source5', 0.8185682944847634,
        0.9266232565987541],
       ['Object7', 'Property1', 337793, 'Source5', 0.8185682944847634,
        0.9266232257763465],
       ['Object7', 'Property3', 361249, 'Source5', 0.8185682944847634,
        0.9266233207044674],
       ['Object8', 'Property1', 433516, 'Source5', 0.8185682944847634,
        0.9266235030519351],
       ['Object8', 'Property3', 972520, 'Source5', 0.8185682944847634,
        0.700865008808545],
       ['Object9', 'Property1', 862949, 'Source5', 0.8185682944847634,
        0.7008407385005504],
       ['Object9', 'Property3', 572373, 'Source5', 0.8185682944847634,
        0.7008414822971586],
       ['Object10', 'Property1', 835321, 'Source5', 0.8185682944847634,
        0.7008418847506334],
       ['Object10', 'Property3', 526281, 'Source5', 0.8185682944847634,
        0.7008413387662293],
       ['Object1', 'Property1', 815569, 'Source2', 0.6724227617758937,
        0.6370517239796115],
       ['Object1', 'Property3', 745886, 'Source2', 0.6724227617758937,
        0.6370522136496279],
       ['Object2', 'Property1', 513198, 'Source2', 0.6724227617758937,
        0.6370542554190868],
       ['Object2', 'Property3', 735585, 'Source2', 0.6724227617758937,
        0.6370521402566727],
       ['Object3', 'Property1', 672332, 'Source2', 0.6724227617758937,
        0.6370528164310512],
       ['Object3', 'Property3', 712833, 'Source2', 0.6724227617758937,
        0.6370521826548303],
       ['Object4', 'Property1', 904358, 'Source2', 0.6724227617758937,
        0.6370518850759718],
       ['Object4', 'Property3', 969666, 'Source2', 0.6724227617758937,
        0.6370516167348135],
       ['Object5', 'Property1', 667107, 'Source2', 0.6724227617758937,
        0.6370520239221577],
       ['Object5', 'Property3', 816028, 'Source2', 0.6724227617758937,
        0.6370541682334611],
       ['Object6', 'Property1', 567388, 'Source2', 0.6724227617758937,
        0.6370519950465026],
       ['Object6', 'Property3', 895711, 'Source2', 0.6724227617758937,
        0.6370517762260438],
       ['Object7', 'Property1', 889516, 'Source2', 0.6724227617758937,
        0.6370531859328545],
       ['Object7', 'Property3', 538773, 'Source2', 0.6724227617758937,
        0.6370526529615602],
       ['Object8', 'Property1', 707788, 'Source2', 0.6724227617758937,
        0.637052282354627],
       ['Object8', 'Property3', 925283, 'Source2', 0.6724227617758937,
        0.6370574733588588],
       ['Object9', 'Property1', 664800, 'Source2', 0.6724227617758937,
        0.637090994476156],
       ['Object9', 'Property3', 734677, 'Source2', 0.6724227617758937,
        0.6370580245283157],
       ['Object10', 'Property1', 995033, 'Source2', 0.6724227617758937,
        0.6370520352088567],
       ['Object10', 'Property3', 888943, 'Source2', 0.6724227617758937,
        0.6370527345066801],
       ['Object1', 'Property1', 553777, 'Source4', 0.672421150252962,
        0.6370515516421005],
       ['Object1', 'Property3', 953423, 'Source4', 0.672421150252962,
        0.6370512380594099],
       ['Object2', 'Property1', 667019, 'Source4', 0.672421150252962,
        0.6370518593187198],
       ['Object2', 'Property3', 612723, 'Source4', 0.672421150252962,
        0.6370521244776337],
       ['Object3', 'Property1', 892948, 'Source4', 0.672421150252962,
        0.6370513940613753],
       ['Object3', 'Property3', 857726, 'Source4', 0.672421150252962,
        0.6370512644311441],
       ['Object4', 'Property1', 683610, 'Source4', 0.672421150252962,
        0.6370519160673309],
       ['Object4', 'Property3', 506381, 'Source4', 0.672421150252962,
        0.6370518496997077],
       ['Object5', 'Property1', 938949, 'Source4', 0.672421150252962,
        0.6370511101159391],
       ['Object5', 'Property3', 796398, 'Source4', 0.672421150252962,
        0.637055622196093],
       ['Object6', 'Property1', 987975, 'Source4', 0.672421150252962,
        0.6370510093063914],
       ['Object6', 'Property3', 646798, 'Source4', 0.672421150252962,
        0.6370516725586135],
       ['Object7', 'Property1', 857391, 'Source4', 0.672421150252962,
        0.6370538701817853],
       ['Object7', 'Property3', 967582, 'Source4', 0.672421150252962,
        0.6370510940520888],
       ['Object8', 'Property1', 529243, 'Source4', 0.672421150252962,
        0.6370534628425845],
       ['Object8', 'Property3', 847254, 'Source4', 0.672421150252962,
        0.6370540406090474],
       ['Object9', 'Property1', 547016, 'Source4', 0.672421150252962,
        0.6370534548504261],
       ['Object9', 'Property3', 751132, 'Source4', 0.672421150252962,
        0.637055116098844],
       ['Object10', 'Property1', 617617, 'Source4', 0.672421150252962,
        0.6370525818768075],
       ['Object10', 'Property3', 835386, 'Source4', 0.672421150252962,
        0.6370531052947054],
       ['Object1', 'Property2', 746472, 'Source1', 0.8118422091111772,
        0.6970612002742946],
       ['Object2', 'Property2', 941491, 'Source1', 0.8118422091111772,
        0.6970598502774253],
       ['Object3', 'Property2', 583065, 'Source1', 0.8118422091111772,
        0.6970614666682053],
       ['Object4', 'Property2', 766544, 'Source1', 0.8118422091111772,
        0.6970608486711837],
       ['Object5', 'Property2', 651055, 'Source1', 0.8118422091111772,
        0.6970611118039152],
       ['Object6', 'Property2', 501781, 'Source1', 0.8118422091111772,
        0.6970612316307284],
       ['Object7', 'Property2', 957313, 'Source1', 0.8118422091111772,
        0.6970597036528725],
       ['Object8', 'Property2', 596620, 'Source1', 0.8118422091111772,
        0.6970663533477143],
       ['Object9', 'Property2', 762123, 'Source1', 0.8118422091111772,
        0.6970610799364332],
       ['Object10', 'Property2', 827050, 'Source1', 0.8118422091111772,
        0.6970626701013688],
       ['Object1', 'Property2', 901020, 'Source3', 0.8185695437826259,
        0.7008425649297617],
       ['Object2', 'Property2', 679921, 'Source3', 0.8185695437826259,
        0.700842887464837],
       ['Object3', 'Property2', 653471, 'Source3', 0.8185695437826259,
        0.7008420686404144],
       ['Object4', 'Property2', 931189, 'Source3', 0.8185695437826259,
        0.7008439174595532],
       ['Object5', 'Property2', 892642, 'Source3', 0.8185695437826259,
        0.7008413553413572],
       ['Object6', 'Property2', 602508, 'Source3', 0.8185695437826259,
        0.700841972239528],
       ['Object7', 'Property2', 736727, 'Source3', 0.8185695437826259,
        0.700842785058513],
       ['Object8', 'Property2', 832536, 'Source3', 0.8185695437826259,
        0.7008413917267241],
       ['Object9', 'Property2', 722236, 'Source3', 0.8185695437826259,
        0.7008447232199165],
       ['Object10', 'Property2', 631083, 'Source3', 0.8185695437826259,
        0.8458754154610832],
       ['Object1', 'Property2', 862526, 'Source5', 0.8185682944847634,
        0.7008438264892565],
       ['Object2', 'Property2', 781822, 'Source5', 0.8185682944847634,
        0.7008415679246203],
       ['Object3', 'Property2', 987522, 'Source5', 0.8185682944847634,
        0.700840393625879],
       ['Object4', 'Property2', 978930, 'Source5', 0.8185682944847634,
        0.7008415185202282],
       ['Object5', 'Property2', 602032, 'Source5', 0.8185682944847634,
        0.7008434248263087],
       ['Object6', 'Property2', 986353, 'Source5', 0.8185682944847634,
        0.7008403862559751],
       ['Object7', 'Property2', 695477, 'Source5', 0.8185682944847634,
        0.7008437364757457],
       ['Object8', 'Property2', 588402, 'Source5', 0.8185682944847634,
        0.7008557920731633],
       ['Object9', 'Property2', 643834, 'Source5', 0.8185682944847634,
        0.7008429180583209],
       ['Object10', 'Property2', 631083, 'Source5', 0.8185682944847634,
        0.8458754154610832],
       ['Object1', 'Property2', 168208, 'Source2', 0.6724227617758937,
        0.7549476384600062],
       ['Object2', 'Property2', 432090, 'Source2', 0.6724227617758937,
        0.7549481145311739],
       ['Object3', 'Property2', 152970, 'Source2', 0.6724227617758937,
        0.7549477458997332],
       ['Object4', 'Property2', 475263, 'Source2', 0.6724227617758937,
        0.754947973795687],
       ['Object5', 'Property2', 388816, 'Source2', 0.6724227617758937,
        0.7549482900087604],
       ['Object6', 'Property2', 319997, 'Source2', 0.6724227617758937,
        0.7549482919485612],
       ['Object7', 'Property2', 269456, 'Source2', 0.6724227617758937,
        0.7549477942149936],
       ['Object8', 'Property2', 323152, 'Source2', 0.6724227617758937,
        0.7549481692930605],
       ['Object9', 'Property2', 286530, 'Source2', 0.6724227617758937,
        0.7549479310975542],
       ['Object10', 'Property2', 175236, 'Source2', 0.6724227617758937,
        0.6370527230695423],
       ['Object1', 'Property2', 168208, 'Source4', 0.672421150252962,
        0.7549476384600062],
       ['Object2', 'Property2', 432090, 'Source4', 0.672421150252962,
        0.7549481145311739],
       ['Object3', 'Property2', 152970, 'Source4', 0.672421150252962,
        0.7549477458997332],
       ['Object4', 'Property2', 475263, 'Source4', 0.672421150252962,
        0.754947973795687],
       ['Object5', 'Property2', 388816, 'Source4', 0.672421150252962,
        0.7549482900087604],
       ['Object6', 'Property2', 319997, 'Source4', 0.672421150252962,
        0.7549482919485612],
       ['Object7', 'Property2', 269456, 'Source4', 0.672421150252962,
        0.7549477942149936],
       ['Object8', 'Property2', 323152, 'Source4', 0.672421150252962,
        0.7549481692930605],
       ['Object9', 'Property2', 286530, 'Source4', 0.672421150252962,
        0.7549479310975542],
       ['Object10', 'Property2', 856218, 'Source4', 0.672421150252962,
        0.6370532205985824]], dtype=object)

In [15]:
list_1=data_truth_.to_numpy()

In [16]:
def function(list_A,list_B):
    binary=[]
    search_list = [tuple(li[:-3]) for li in list_B]
    for ser_item in search_list:
        if ser_item in list_A:
            binary.append(1)
        else:
            binary.append(0)
    return binary

In [17]:
function(list_,list__)

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [28]:
function(list_1,list__)

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [29]:
!pip install scikit-learn
import sklearn

Requirement already satisfied: scikit-learn in /Users/admin/miniconda3/lib/python3.9/site-packages (0.24.2)
Requirement already satisfied: numpy>=1.13.3 in /Users/admin/miniconda3/lib/python3.9/site-packages (from scikit-learn) (1.20.3)
Requirement already satisfied: scipy>=0.19.1 in /Users/admin/miniconda3/lib/python3.9/site-packages (from scikit-learn) (1.7.1)
Requirement already satisfied: joblib>=0.11 in /Users/admin/miniconda3/lib/python3.9/site-packages (from scikit-learn) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/admin/miniconda3/lib/python3.9/site-packages (from scikit-learn) (2.2.0)

In [30]:
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [31]:
precision_score(res_truth,res)

NameError: name 'res_truth' is not defined

In [ ]:
accuracy_score(res_truth,res)

In [ ]:
recall_score(res,resp)

In [ ]:
f1_score(res_truth,res)